version: "3.9"
services:
  frontend:
    build: .
    ports:
      - "8080:80"
    links:
      - backend
    depends_on:
      - backend
  backend:
    image: dfrnks/dockerfile-example-backend
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
  redis:
    image: redis
  db:
    image: postgres
    volumes:
      - ./.postgres-data:/var/lib/postgresql/data
    environment: 
      POSTGRES_PASSWORD: password
  adminer:
    image: adminer
    ports:
      - 8090:8080
    depends_on:
      - db